export const products = [
  {
    id: 1,
    name: "Watch Holder",
    description:
      "Support de bureau en silicone pour Apple Watch Series 8, 7, 6, 5, 4, 3, 2, 1, SE, support de charge S6, support de chargeur iWatch, accessoires intelligents",
    comment: "Commentaire 1",
    price: "4.85",
    link: "lien1.com",
    image1: "/images/products/1.png",
    new: false,
    popular: false,
  },
  {
    id: 2,
    name: "Support de manette",
    description:
      "Support de manette de jeu universel, support de manette, support de manette de jeu, support pour Switch Pro, PS5, Xbox Series, T1",
    comment: "Commentaire 2",
    price: "17.5",
    link: "lien2.com",
    image1: "/images/products/2.png",
    new: false,
    popular: true,
  },
  {
    id: 3,
    name: "Mini Console",
    description:
      "Mini Console de Jeu Vidéo Rétro pour Enfants, Jouet Portable, 8 Bits, 3,0 pouces, Écran Couleur LCD, 400 Jeux Intégrés, Accessoire de Joueur, Tout Petit",
    comment: "Commentaire 3",
    price: "7.05",
    link: "lien3.com",
    image1: "/images/products/3.png",
    new: false,
    popular: false,
  },
  {
    id: 4,
    name: "Mini dock Switch",
    description:
      "Concentrateur TYPE-C de station d'accueil portable Nintendo Switch avec HDMI et USB 3.0 parfait pour les voyages et les jeux",
    comment: "Commentaire 4",
    price: "6.08",
    link: "lien4.com",
    image1: "/images/products/4.png",
    new: true,
    popular: true,
  },
  {
    id: 5,
    name: "Manchon de protection",
    description:
      "One Piece-Manchon de protection pour câble de données de téléphone, anime, dessin animé, Zoro, Chopper, Luffy, mignon, iPhone, Samsung, ISub, cadeau de câble de charge",
    comment: "Commentaire 5",
    price: "1.78",
    link: "lien5.com",
    image1: "/images/products/5.png",
    new: false,
    popular: false,
  },
  {
    id: 6,
    name: "Grip magnétique",
    description:
      "CapGrip magnétique pour téléphone avec charge sans fil, Obturateur Booster Selfie, Magsafe, iPhone 14, 13, 12, Vlog, Poignée de prise de vue",
    comment: "Commentaire 6",
    price: "14.37",
    link: "lien6.com",
    image1: "/images/products/6.png",
    new: false,
    popular: false,
  },
  {
    id: 7,
    name: "Écouteurs sans fil",
    description:
      "Monster-Écouteurs sans fil Bluetooth 5.3 d'origine, écouteurs de jeu TWS, casque avec couvercle rabattable RVB, faible latence, XKT15, nouveau, 2023",
    comment: "Commentaire 7",
    price: "14.75",
    link: "lien7.com",
    image1: "/images/products/7.png",
    new: true,
    popular: false,
  },
  {
    id: 8,
    name: "Cagoule en velours",
    description:
      "Cagoule en velours à capuche pour homme, chapeau en peluche, bonnets thermiques, couvre-chef, cache-cou, sport, écharpe coupe-vent, hiver",
    comment: "Commentaire 8",
    price: "3.40",
    link: "lien8.com",
    image1: "/images/products/8.png",
    new: true,
    popular: false,
  },
  {
    id: 9,
    name: "Écran usb-c",
    description:
      "Nouveau 3.5 Pouces IPS TYPE-C Écran Secondaire Ordinateur CPU GPU RAM HDD MonitorUSB Affichage Pour Freely AIDA64",
    comment: "Commentaire 9",
    price: "16.76",
    link: "lien9.com",
    image1: "/images/products/9.png",
    new: true,
    popular: false,
  },
  {
    id: 10,
    name: "Coque poêle à frire",
    description:
      "Coque arrière drôle de poêle à frire 3D pour iPhone, coque de téléphone en poly XS Max, iPhone 15 Pro, iPhone 14, iPhone 13 Mini, iPhone 12 Pro Max, iPhone 11 Pro, iPhone SE, iPhone 10 X, iPhone 7, iPhone 8, iPhone 6s Plus",
    comment: "Commentaire 10",
    price: "7.20",
    link: "lien10.com",
    image1: "/images/products/10.png",
    new: true,
    popular: false,
  },
];
